name: modern_manaba
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  html: ^0.15.4

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.5
  lints: ^1.0.0
